name: CI

on: [push, pull_request]

env:
  RUST_MINVERSION: 1.41.1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust:
        - stable
        - beta
        - nightly
        - 1.44.0

        include:
        - rust: stable
          features: ''
        - rust: stable
          features: '--no-default-features --features alloc'
        - rust: stable
          features: '--no-default-features'

        - rust: beta
          features: ''
        - rust: beta
          features: '--no-default-features --features alloc'
        - rust: beta
          features: '--no-default-features'

        - rust: nightly
          features: ''
        - rust: nightly
          features: '--no-default-features --features alloc'
        - rust: nightly
          features: '--no-default-features'


    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install rust (${{ matrix.rust }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose ${{ matrix.features }}

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose ${{ matrix.features }}

      - name: Doc
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --verbose ${{ matrix.features }}
